====================
Algebraic Structures
====================

In this chapter, we'll meet a good range of important
algebraic structures, using a simple running example 
throughout. The example serves two purposes. 

First it's so simple, that most of the proofs we'll 
need along the way are easy to produce by basic case
analysis; so we can focus on key algebraic ideas rather
than on tedious proof details. 

Second, the example will show that we've moved beyond
algebra involving numbers to  geometry involving things 
that are other than numerical (e.g., equilateral triangles
and their symmetry-preserving rotations). 

We'll have points (triangles), differences between them
yielding "vectors" (symmetry-preserving rotations), and 
"vectors" in turn acting on points by displacement (in
our example, by rotational displacements). 

When actions can be added and subtracted, and also scalar 
multiplied by scalars from a ring (addition, subtraction, 
and multiplication), then we have a module. When scalars
can be dividing, giving rise to fractions, then our set 
of "vectors" has to be closed under scalar multiplication
by fractions. 

A key aim of ours throughout is to see how to develop and
formalize an algebra for geometric or temporal reasoning, 
with a torsor of points, differences between them yielding
a actions ("vectors"), that themselves belong to a module 
(no *fractions of actions*) or vector space (*fractions of actions!*). 

It'll will take a while to get there. Let's get started. 
