lean_source/mkdoc.py 00_Introduction 00_unit_title
lean_source/mkdoc.py 00_Introduction 01_abstract_language_and_thought
lean_source/mkdoc.py 00_Introduction 02_this_class

lean_source/mkdoc.py 01_Propositional_Logic 00_unit_title
lean_source/mkdoc.py 01_Propositional_Logic 01_formal_languages
lean_source/mkdoc.py 01_Propositional_Logic 02_subset_prop_logic
lean_source/mkdoc.py 01_Propositional_Logic 03_prop_logic_syn_sem

