===============
Predicate Logic
===============
**********************
Propositions are Types
**********************
*******************
From Truth to Proof
*******************
*********
Functions
*********
**********
Predicates
**********
***********
Connectives
***********

We get them all from predicate logic, with meanings
defined by inference rules that straightforwardly 
generalize those from propositonal logic.

.. code-block:: lean

  def x := 5

***********
Quantifiers
***********

Among which are quantifiers over types giving rise to
parametric polymorphism, where the type of element that
is handled by an operation can vary with no changes in
the definition of the operation itself.

.. code-block:: lean

  def y := 5

***************
Inference Rules
***************

.. code-block:: lean

  def z := 5

