############
Introduction
############
Computing foundations are not to be found in the formal semantics 
of programming languages but in the abstract mathematical semantics
of the worlds that are to be programmed. 

Formalized abstract mathematics will provide a powerful new 
foundation for software-intensive systems of the future. Our
most successful models of reality are deeply mathematical. As
examples, physics rests on the rigorous, abstract mathematics
of topological manifolds, tangent bundles, vector and tensor
fields, etc. 

Until recently -- and still mostly today -- abstract mathematics
has been largely a paper and pencil exercise, but we are seeing 
the emergence of rich libraries of formalized abstract mathematics
driven the the embrace of type theory foundations and constructive 
logic proof assistants by some parts of the mathematics research 
community.

As an historical development, their work follows the long history
of use of such tools in software engineering and languages research,
primarily for the specification and verification of properties of 
software. The mathematics research community has a different agenda:
to formalize and substantially automate reasoning across subfields
of abstract mathematical discourse. 

They key insight behind this effort is that we in the computer 
science community can now take advantage of what the mathematics
research community is providing, by using abstract mathematics in
automated forms for software development. That is, having helped to
sow a research in automated mathematics, we now propose to import
what they are producing to build foundationally verified, abstract
mathematical semantics for next generation software systems. 

As an example, we have developed an formal mathematical definition 
of affine spaces and their surrouding spaces of affine coordinate 
systems as a way to bring sanity to handling of multiple physical
dimensions and arbitrary coordinate systems imposed upon them, and
with automated translations between coordinate systems. But this 
is just a start. Hang around for more later.

As for the rest of this document, it's just a set of rough notes
from part of a course related to these ideas. It's not recommended
to spend much time on this material at this point. I'll be pulling
it together in the weeks to come.



